---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sample-go-app
spec:
  replicas: 2
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sample-go-app
    spec:
      containers:
      - name: samplego
        image: azcontregxpto.azurecr.io/samplego:$BUILD_NUMBER
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: $KUBERNETES_SECRET_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: sample-go-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
app: sample-go-app
